---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/maqshaf/api
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
